export declare class Query {
    lessThan: (key: any, value: any) => any;
    lessThanOrEqualTo: (key: any, value: any) => any;
    greaterThan: (key: any, value: any) => any;
    greaterThanOrEqualTo: (key: any, value: any) => any;
    notEqualTo: (key: any, value: any) => any;
    containedIn: (key: any, value: any) => any;
    notContainedIn: (key: any, value: any) => any;
    exists: (key: any) => any;
    notExists: (key: any) => any;
    ascending: (key: any) => any;
    descending: (key: any) => any;
    skip: (value: any) => any;
    limit: (value: any) => any;
    or: () => any;
    nor: () => any;
    not: () => any;
    and: () => any;
    baseDir: any;
    masterLocale: any;
    content_type_uid: any;
    type: string;
    single: boolean;
    private _query;
    constructor();
    equalTo(key: any, value: any): this;
    where(key: any, value: any): this;
    count(): this;
    query(query: any): this;
    tags(values: any): this;
    includeCount(): this;
    language(language_code: any): this;
    includeReferences(): this;
    excludeReferences(): this;
    includeContentType(): this;
    addParam(key: any, value: any): this;
    getQuery(): any;
    regex(key: any, value: any, options: any): this;
    only(fields: any): this;
    except(fields: any): this;
    queryReferences(query: any): this;
    find(): Promise<{}>;
    private queryOnReferences;
    findOne(): Promise<{}>;
    private findReferences;
    private includeReferencesI;
    private preProcess;
    private postProcessResult;
}
